### ISSUE TITLE
Checklist before first release

### ISSUE THREAD

**Issue by rithviknishad** [rithviknishad/prosumer#1]
## Priority P1

- [ ] Realtime state variables to be broadcasted to the EMS over MQTT
- [ ] Profile for Consumption subsystem
- [ ] Virtual Subsystem for Import/Export

## Priority P2

- [ ] Base export price based on subsystems asset value payback period
- [ ] Export price based on grid Pd/Pg ratio
